# This is a basic workflow that is manually triggered

name: Sync on Github - Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Foo is bar - Sync remote repository from another remote repository
      run: gh repo sync wfriends/wknd
