# This is a basic workflow that is manually triggered

name: Sync on Github - Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

permissions: write-all
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Foo is bar - Sync remote repository from another remote repository
      run: gh repo sync w-friends/wknd --source cwoeltge/wknd
      env:
        GH_TOKEN: ${{ github.token }}
        GH_PAT: ${{ secrets.PAT }}
        GH_REPO: ${{ github.repository }}
        OWNER: ${{ github.repository_owner }}
        REPO: ${{ github.repository }}
        GH_DEBUG: 1

